package net.semperidem.fishingclub.entity;

import net.minecraft.entity.*;
import java.util.HashMap;

import static net.minecraft.entity.EntityType.*;

public class EntityWeights {
    private static final HashMap<EntityType<?>, Double> ENTITY_TYPE_TO_WEIGHT_MAP = new HashMap<>();
    private static final double DEFAULT = 1;
    public static double getEntityWeight(EntityType<?> entityType) {
        return ENTITY_TYPE_TO_WEIGHT_MAP.getOrDefault(entityType, DEFAULT);
    }

    static {
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ALLAY, 0.001);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ARMOR_STAND, 1.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ARROW, 0.001);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(AXOLOTL, 0.1);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(BAT, 0.05);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(BEE, 0.01);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(BLAZE, 10.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(BOAT, 25.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(CHEST_BOAT, 40.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(CAT, 5.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(CHICKEN, 2.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(COW, 200.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(CREEPER, 10.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(DOLPHIN, 80.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(DONKEY, 300.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(DROWNED, 50.0); // Similar to Zombie
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ELDER_GUARDIAN, 2000.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ENDER_DRAGON, 100000.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ENDERMAN, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ENDERMITE, 0.2);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(EVOKER, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(FOX, 5.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(FROG, 0.3);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(GIANT, 40000.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(GLOW_SQUID, 7.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(GOAT, 60.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(GUARDIAN, 200.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(HOGLIN, 500.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(HORSE, 400.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(HUSK, 35.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ILLUSIONER, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(IRON_GOLEM, 3000.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(LLAMA, 250.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(MAGMA_CUBE, 10.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(MULE, 250.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(MOOSHROOM, 250.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(OCELOT, 25.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PANDA, 100.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PARROT, 0.05);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PIG, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PIGLIN, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PIGLIN_BRUTE, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PILLAGER, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(POLAR_BEAR, 300.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PUFFERFISH, 0.5);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(RABBIT, 1.5);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(RAVAGER, 1500.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SALMON, 1.5);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SHEEP, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SHULKER, 160.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SILVERFISH, 0.2);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SKELETON, 10.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SKELETON_HORSE, 30.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SLIME, 500.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SNOW_GOLEM, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SPIDER, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(SQUID, 7.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(STRAY, 10.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(STRIDER, 250.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(TADPOLE, 0.01);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(TRIDENT, 2.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(TRADER_LLAMA, 250.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(TROPICAL_FISH, 0.7);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(TURTLE, 150.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(VILLAGER, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(VINDICATOR, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(WANDERING_TRADER, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(WARDEN, 3000.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(WITCH, 45.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(WITHER, 300.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(WITHER_SKELETON, 15.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(WOLF, 15.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ZOGLIN, 500.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ZOMBIE, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ZOMBIE_HORSE, 200.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ZOMBIE_VILLAGER, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(ZOMBIFIED_PIGLIN, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(PLAYER, 50.0);
        ENTITY_TYPE_TO_WEIGHT_MAP.put(FISHING_BOBBER, 0.05);
    }
}
